import './globals.css';

import type { Metadata } from 'next';

import Providers from '@/components/Providers';
import { initMSW } from '@/mocks';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (process.env.NODE_ENV === 'development') {
    initMSW();
  }

  return (
    <html lang="en">
      <body>
        <div className="max-w-[480px] w-full h-dvh mx-auto flex flex-col items-center justify-center">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
